### ISSUE TITLE
x64dbg crash

### ISSUE THREAD

**Issue by ghost** [mrexodia/DotNetPluginCS#4]
![asdsa](https://cloud.githubusercontent.com/assets/17880848/22168872/ea3119e0-df95-11e6-9b04-d5bf72dc7442.gif)

**Comment by adams85** [comment]
You've been bitten by [this](https://stackoverflow.com/questions/9536628/p-invoke-causes-crash-on-method-with-struct-and-callback-parameters).

The P/Invoke code didn't keep references to the callback delegates so they were GC'd at random points in time. Now this is corrected.
